name: TxT
favicon: null
layout_spectrum: 0.41212177090346813
typography_spectrum: 0.5672949135769159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3748003183864057
  lightness: 0.5544501491822302
  saturation: 0.7168863366823643
  rhythmicContrast: 0.3757636931259185
purpose: []
